apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/cert-manager.cert-manager: ""
  name: cert-manager
  namespace: cert-manager
spec:
  installPlanApproval: Automatic
  name: cert-manager
  source: operatorhubio-catalog
  sourceNamespace: olm
